<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>BatchCraft.Tests</AssemblyName>
    <UseWindowsForms>true</UseWindowsForms>
    <NuGetAudit>true</NuGetAudit>
    <NuGetAuditMode>all</NuGetAuditMode>
  </PropertyGroup>
  <ItemGroup><ProjectReference Include="..\BatchCraft.App\BatchCraft.App.csproj" /></ItemGroup>
</Project>
