<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Tools.InnoSetup" Version="6.7.3" GeneratePathProperty="true" PrivateAssets="all" />
  </ItemGroup>
  <Target Name="BuildInstaller" AfterTargets="Build">
    <Exec Command="&quot;$(InnoSetupCompiler)&quot; &quot;$(MSBuildProjectDirectory)\BatchCraft.iss&quot;" />
  </Target>
</Project>
